# Generated by Django 3.0.6 on 2020-05-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r0_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('max_dur', models.PositiveSmallIntegerField(choices=[(30, '30'), (45, '45')], default=45)),
                ('cont_dur', models.PositiveSmallIntegerField(default=7)),
                ('mult', models.PositiveSmallIntegerField(choices=[(0, 'assume case accurate'), (1, 'multiply cases by 10'), (2, 'death rate .01'), (3, 'death rate .02')], default=0)),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('output_url', models.URLField(unique=True)),
                ('day_zero', models.DateTimeField(verbose_name='day zero')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_day_since_zero', models.PositiveSmallIntegerField()),
                ('_new_cases', models.PositiveIntegerField(default=0)),
                ('_new_deaths', models.PositiveIntegerField(default=0)),
                ('paramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projection.Parameters')),
            ],
        ),
    ]
