# Generated by Django 3.0.6 on 2020-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='_day_since_zero',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='_new_cases',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='_new_deaths',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='date_updated',
            field=models.DateField(null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='day_zero',
            field=models.DateField(null=True, verbose_name='day zero'),
        ),
    ]
