# Generated by Django 3.0.6 on 2020-05-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0002_auto_20200528_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]

    atomic=False
