# Generated by Django 3.0.6 on 2020-05-29 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0003_auto_20200528_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='day_zero',
            field=models.DateField(default=datetime.date(2020, 2, 29), null=True, verbose_name='day zero'),
        ),
    ]
