# Generated by Django 3.0.6 on 2020-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0004_auto_20200529_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='output_url',
            field=models.URLField(),
        ),
    ]
