# Generated by Django 3.0.6 on 2020-06-11 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0006_auto_20200606_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='_date_updated',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='day_zero',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 0, 0), null=True, verbose_name='day zero'),
        ),
    ]
