# Generated by Django 3.0.6 on 2020-06-11 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0007_auto_20200611_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='time_updated',
            field=models.TimeField(null=True, verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='date_updated',
            field=models.DateField(null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='day_zero',
            field=models.DateField(default=datetime.date(2020, 2, 29), null=True, verbose_name='day zero'),
        ),
    ]
