# Generated by Django 3.0.6 on 2020-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0008_auto_20200611_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='model_size',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
